[Refactor]: Refactored helper functions
PestoTech/project-the-remotants-backend pull request #15
Opened 2018-07-16 19:18 UTC by Saumya29

2018-07-16 22:35 UTC, Saumya29 commented on src/helpers/handleHash.js
> +  const hash = await bcrypt.hash(plainText, (+productionConstants.SALT_ROUNDS));
Converting string to number

2018-07-16 23:09 UTC, anshurathee commented on src/helpers/handleHash.js
> +  const hash = await bcrypt.hash(plainText, (+productionConstants.SALT_ROUNDS));
Use Number()

2018-07-16 23:49 UTC, anshurathee requested changes

2018-07-16 23:49 UTC, anshurathee commented on src/routes/dashboard.js
> +      ...req.body,
spread it before, and then pass ownerID

2018-07-16 23:49 UTC, anshurathee commented on src/routes/dashboard.js
> +route.post('/orgSetup', async (req, res) => {
use route constants

2018-07-16 23:49 UTC, anshurathee commented on src/routes/dashboard.js
>  route.post('/setup', async (req, res) => {
use route constants

2018-07-16 23:49 UTC, anshurathee commented on src/routes/dashboard.js
>  route.get('/', (req, res) => {
use route constants

2018-07-16 23:49 UTC, anshurathee commented on src/routes/dashboard.js
> +// export const addOrganisation = async (
remove the commented out code.

2018-07-17 17:50 UTC, Saumya29 commented on src/routes/dashboard.js
>  route.post('/setup', async (req, res) => {
Done

2018-07-17 17:51 UTC, Saumya29 commented on src/routes/dashboard.js
>  route.get('/', (req, res) => {
Done

2018-07-17 17:51 UTC, Saumya29 commented on src/routes/dashboard.js
> +// export const addOrganisation = async (
Done

2018-07-17 19:10 UTC, Saumya29 commented on src/routes/dashboard.js
>  route.post('/setup', async (req, res) => {
Done

2018-07-17 19:14 UTC, anshurathee approved these changes

2018-07-17 19:16 UTC, merged